server:
  host: ${SERVER_HOST:localhost}
  port: ${SERVER_PORT:8080}
  path: ${SERVER_PATH:}

spring:
  application:
    name: auction-project
  profiles:
    active: ${ENV:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/auction_swd_392}
    username: ${SPRING_DATASOURCE_USER:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-score
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        reWriteBatchedInserts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        show_sql: false
        jdbc:
          batch_size: 100
        order_inserts: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  firebase:
    project-name: ${SPRING_FIREBASE_PROJECT_NAME:auction}
    config-path: ${SPRING_FIREBASE_CONFIG_PATH:path}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    from: ${MAIL_FROM:mail.from}
    properties:
      mail.smtp:
        starttls.enable: 'true'
        auth: 'true'
    test-connection: false
  security:
    user:
      name: sample
      password: password
    api-key:
      - path: /api/v1/system/user/admin/create
        key: zLp63CqnIjCN4n9z
    path-matcher:
      ignore-authorization:
        - /webjars/swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /webjars/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /actuator/**
        - /mock/**
        - /api/v1/app/*/public/**
        - /api/v1/media/**
        - /api/v1/auth/**
        - /api/v1/location/**
        - /api/v1/payment/**
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/${spring.firebase.project-name}
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
  minio:
    check-bucket: false
    url: https://api-minio.ic-fpt.click
    access-key: WA9jLKOQ7VOLM3J3ObNs
    secret-key: hbZhS6WvtjYv3TAon2UV0Z4Cvc8wlUrHJrmTJzrp
    bucket: auction
    secure: true
    create-bucket: false
    pre-signed-upload-duration: 60
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 10000
            logger-level: full
          paypal:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_PAYPAL_URL:https://api-m.sandbox.paypal.com}
            logger-level: full
          currency:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_CURRENCY_URL:https://open.er-api.com}
            logger-level: full
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRING_DOC_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    operations-sorter: alpha
    tags-sorter: alpha
    url: ${server.path}/v3/api-docs
    config-url: ${server.path}/v3/api-docs/swagger-config
  server-urls: http://localhost:${server.port},/

management:
  endpoints:
    web:
      exposure:
        include: 'health'

logging:
  level:
    com.free.swd_392: trace
    org.springframework.security: debug

paypal:
  client-id: ${PAYPAL_CLIENT_ID:AcsOD22Hu8gEJTzaw-VkYmzcbZ4sGE-KTl1q6nhR2R4zn0VU8JcT1NfzEp3S9-31BEPoUWu2PXkoEWYH}
  secret-key: ${PAYPAL_SECRET_KEY:EM-5YL4AsRjxTW5P6S96uzsbw-Fb5b2t2OXaZudzt5ZkSU8XbVkRXh1Slia9predd589OA-fh8w69Cg7}
  approve-url: ${PAYPAL_DEPOSIT_URL:http://${server.host}:${server.port}${server.path}/api/v1/payment/checkout/approve/}
  cancel-url: ${PAYPAL_DEPOSIT_URL:http://${server.host}:${server.port}${server.path}/api/v1/payment/checkout/cancel/}
  app-redirect-url: ${APP_REDIRECT_URL:http://localhost:3000/order}
