apiVersion: v1
kind: Pod
metadata:
  name: test-ci
  labels:
    app: jenkins-ci
spec:
  containers:
    - name: builder
      image: docker.io/distrolessman/auto-ci:jre-17.0.8-alpine-3.18
      command:
        - cat
      tty: true
    - name: pusher
      image: gcr.io/kaniko-project/executor:v1.20.1-debug
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /kaniko/.docker
          name: jenkins-docker-cfg

  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: docker-credentials
              items:
                - key: .dockerconfigjson
                  path: config.json
